works_to_show: 6
reviews_to_show: 3

collections:
  works:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"
      host: true
      show: true
      adapted: true
